### ISSUE TITLE
[DOCS] Add documentation

### ISSUE THREAD

**Issue by yashchaudhari008** [yashchaudhari008/minime#14]
### TODOs:
- [ ] Add project details
- [ ] Add basic setup information about how to use this application
- [ ] Add contribution guide
- [ ] Add status indicator and other small widgets
- [ ] Add license/ code-of-conduct information
- [ ] PR template
- [ ] Guidelines for creating issue
- [ ] Branching strategy details

**Comment by alvin-dennis** [comment]
can i work on code of conduct and pr template? @yashchaudhari008 pls assign me under hacktoberfest
